// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATGNDXzDkXFl7oOWHZo7S3OquLXg5JwtM',
    appId: '1:644528533489:web:5fa2f9f324fb0b9a6ade50',
    messagingSenderId: '644528533489',
    projectId: 'doit-766f8',
    authDomain: 'doit-766f8.firebaseapp.com',
    storageBucket: 'doit-766f8.appspot.com',
    measurementId: 'G-FR2TNS81JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJaEfJIhUfiwo4jCYeCNbFyjVmHy0JAT0',
    appId: '1:644528533489:android:995250e33d68c55c6ade50',
    messagingSenderId: '644528533489',
    projectId: 'doit-766f8',
    storageBucket: 'doit-766f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN_bn5UoNzmaD7LTaSWN50vpkZjgvydQw',
    appId: '1:644528533489:ios:661f051d79f29f306ade50',
    messagingSenderId: '644528533489',
    projectId: 'doit-766f8',
    storageBucket: 'doit-766f8.appspot.com',
    iosClientId: '644528533489-vasrjlhjut52uq87nuvp2lrpb9op6kep.apps.googleusercontent.com',
    iosBundleId: 'com.example.dooit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN_bn5UoNzmaD7LTaSWN50vpkZjgvydQw',
    appId: '1:644528533489:ios:661f051d79f29f306ade50',
    messagingSenderId: '644528533489',
    projectId: 'doit-766f8',
    storageBucket: 'doit-766f8.appspot.com',
    iosClientId: '644528533489-vasrjlhjut52uq87nuvp2lrpb9op6kep.apps.googleusercontent.com',
    iosBundleId: 'com.example.dooit',
  );
}
